const strings = {
    "RKG": {
        tracks: {
            0x08: "Luigi Circuit",
            0x01: "Moo Moo Meadows",
            0x02: "Mushroom Gorge",
            0x04: "Toad's Factory",
            
            0x00: "Mario Circuit",
            0x05: "Coconut Mall",
            0x06: "DK Snowboard Cross",
            0x07: "Wario's Gold Mine",
            
            0x09: "Daisy Circuit",
            0x0F: "Koopa Cape",
            0x0B: "Maple Treeway",
            0x03: "Grumble Volcano",
            
            0x0E: "Dry Dry Ruins",
            0x0A: "Moonview Highway",
            0x0C: "Bowser's Castle",
            0x0D: "Rainbow Road",
            
            0x10: "GCN Peach Beach",
            0x14: "DS Yoshi Falls",
            0x19: "SNES Ghost Valley 2",
            0x1A: "N64 Mario Raceway",
            
            0x1B: "N64 Sherbet Land",
            0x1F: "GBA Shy Guy Beach",
            0x17: "DS Delfino Square",
            0x12: "GCN Waluigi Stadium",
            
            0x15: "DS Desert Hills",
            0x1E: "GBA Bowser Castle 3",
            0x1D: "N64 DK's Jungle Parkway",
            0x11: "GCN Mario Circuit",
            
            0x18: "SNES Mario Circuit 3",
            0x16: "DS Peach Gardens",
            0x13: "GCN DK Mountain",
            0x1C: "N64 Bowser's Castle",
        },
    
        characters: {
            0x00: "Mario",
            0x01: "Baby Peach",
            0x02: "Waluigi",
            0x03: "Bowser",
            0x04: "Baby Daisy",
            0x05: "Dry Bones",
            0x06: "Baby Mario",
            0x07: "Luigi",
            0x08: "Toad",
            0x09: "Donkey Kong",
            0x0A: "Yoshi",
            0x0B: "Wario",
            0x0C: "Baby Luigi",
            0x0D: "Toadette",
            0x0E: "Koopa Troopa",
            0x0F: "Daisy",
            0x10: "Peach",
            0x11: "Birdo",
            0x12: "Diddy Kong",
            0x13: "King Boo",
            0x14: "Bowser Jr.",
            0x15: "Dry Bowser",
            0x16: "Funky Kong",
            0x17: "Rosalina",
            0x2A: "Medium Mii",
            0x2B: "Small Mii",
            0x2C: "Large Mii",
            0x2D: "Peach Biker Outfit",
            0x2E: "Daisy Biker Outfit",
            0x2F: "Rosalina Biker Outfit",
        },
    
        vehicles: {
            0x00: "Standard Kart S",
            0x01: "Standard Kart M",
            0x02: "Standard Kart L",
            0x03: "Booster Seat",
            0x04: "Classic Dragster",
            0x05: "Offroader",
            0x06: "Mini Beast",
            0x07: "Wild Wing",
            0x08: "Flame Flyer",
            0x09: "Cheep Charger",
            0x0A: "Super Blooper",
            0x0B: "Piranha Prowler",
            0x0C: "Tiny Titan",
            0x0D: "Daytripper",
            0x0E: "Jetsetter",
            0x0F: "Blue Falcon",
            0x10: "Sprinter",
            0x11: "Honeycoupe",
            0x12: "Standard Bike S",
            0x13: "Standard Bike M",
            0x14: "Standard Bike L",
            0x15: "Bullet Bike",
            0x16: "Mach Bike",
            0x17: "Flame Runner",
            0x18: "Bit Bike",
            0x19: "Sugarscoot",
            0x1A: "Wario Bike",
            0x1B: "Quacker",
            0x1C: "Zip Zip",
            0x1D: "Shooting Star",
            0x1E: "Magikruiser",
            0x1F: "Sneakster",
            0x20: "Spear",
            0x21: "Jet Bubble",
            0x22: "Dolphin Dasher",
            0x23: "Phantom",
        },
    
        controllers: {
            0: "Wii Wheel",
            1: "Wiimote + Nunchuck",
            2: "Classic",
            3: "GameCube",
        },
    
        ghostTypes: {
            0x01: "Player's Best Time",
            0x02: "World Record",
            0x03: "Continental Record",
            0x04: "Rival",
            0x05: "Special",
            0x06: "Ghost Race",
            0x07: "Friend Ghost 1",
            0x08: "Friend Ghost 2",
            0x09: "Friend Ghost 3",
            0x0A: "Friend Ghost 4",
            0x0B: "Friend Ghost 5",
            0x0C: "Friend Ghost 6",
            0x0D: "Friend Ghost 7",
            0x0E: "Friend Ghost 8",
            0x0F: "Friend Ghost 9",
            0x10: "Friend Ghost 10",
            0x11: "Friend Ghost 11",
            0x12: "Friend Ghost 12",
            0x13: "Friend Ghost 13",
            0x14: "Friend Ghost 14",
            0x15: "Friend Ghost 15",
            0x16: "Friend Ghost 16",
            0x17: "Friend Ghost 17",
            0x18: "Friend Ghost 18",
            0x19: "Friend Ghost 19",
            0x1A: "Friend Ghost 20",
            0x1B: "Friend Ghost 21",
            0x1C: "Friend Ghost 22",
            0x1D: "Friend Ghost 23",
            0x1E: "Friend Ghost 24",
            0x1F: "Friend Ghost 25",
            0x20: "Friend Ghost 26",
            0x21: "Friend Ghost 27",
            0x22: "Friend Ghost 28",
            0x23: "Friend Ghost 29",
            0x24: "Friend Ghost 30",
            0x25: "Beginner Staff Ghost",
            0x26: "Expert Staff Ghost",
        },
    
        // http://wiibrew.org/wiki/Country_Codes
        countries: {
            0: "None",
            1: "Japan",
    
            8: "Anguilla",
            9: "Antigua and Barbuda",
            10: "Argentina",
            11: "Aruba",
            12: "Bahamas",
            13: "Barbados",
            14: "Belize",
            15: "Bolivia",
            16: "Brazil",
            17: "British Virgin Islands",
            18: "Canada",
            19: "Cayman Islands",
            20: "Chile",
            21: "Colombia",
            22: "Costa Rica",
            23: "Dominica",
            24: "Dominican Republic",
            25: "Ecuador",
            26: "El Salvador",
            27: "French Guiana",
            28: "Grenada",
            29: "Guadeloupe",
            30: "Guatemala",
            31: "Guyana",
            32: "Haiti",
            33: "Honduras",
            34: "Jamaica",
            35: "Martinique",
            36: "Mexico",
            37: "Montserrat",
            38: "Netherlands Antilles",
            39: "Nicaragua",
            40: "Panama",
            41: "Paraguay",
            42: "Peru",
            43: "St. Kitts and Nevis",
            44: "St. Lucia",
            45: "St. Vincent and the Grenadines",
            46: "Suriname",
            47: "Trinidad and Tobago",
            48: "Turks and Caicos Islands",
            49: "United States",
            50: "Uruguay",
            51: "US Virgin Islands",
            52: "Venezuela",
    
            64: "Albania",
            65: "Australia",
            66: "Austria",
            67: "Belgium",
            68: "Bosnia and Herzegovina",
            69: "Botswana",
            70: "Bulgaria",
            71: "Croatia",
            72: "Cyprus",
            73: "Czech Republic",
            74: "Denmark",
            75: "Estonia",
            76: "Finland",
            77: "France",
            78: "Germany",
            79: "Greece",
            80: "Hungary",
            81: "Iceland",
            82: "Ireland",
            83: "Italy",
            84: "Latvia",
            85: "Lesotho",
            86: "Lichtenstein",
            87: "Lithuania",
            88: "Luxembourg",
            89: "F.Y.R of Macedonia",
            90: "Malta",
            91: "Montenegro",
            92: "Mozambique",
            93: "Namibia",
            94: "Netherlands",
            95: "New Zealand",
            96: "Norway",
            97: "Poland",
            98: "Portugal",
            99: "Romania",
            100: "Russia",
            101: "Serbia",
            102: "Slovakia",
            103: "Slovenia",
            104: "South Africa",
            105: "Spain",
            106: "Swaziland",
            107: "Sweden",
            108: "Switzerland",
            109: "Turkey",
            110: "United Kingdom",
            111: "Zambia",
            112: "Zimbabwe",
            113: "Azerbaijan",
            114: "Mauritania (Islamic Republic of Mauritania)",
            115: "Mali (Republic of Mali)",
            116: "Niger (Republic of Niger)",
            117: "Chad (Republic of Chad)",
            118: "Sudan (Republic of the Sudan)",
            119: "Eritrea (State of Eritrea)",
            120: "Djibouti (Republic of Djibouti)",
            121: "Somalia (Somali Republic)",
    
            128: "Taiwan",
            136: "South Korea",
            144: "Hong Kong",
            145: "Macao",
            152: "Indonesia",
            153: "Singapore",
            154: "Thailand",
            155: "Philippines",
            156: "Malaysia",
            160: "China",
    
            168: "U.A.E.",
            169: "India",
            170: "Egypt",
            171: "Oman",
            172: "Qatar",
            173: "Kuwait",
            174: "Saudi Arabia",
            175: "Syria",
            176: "Bahrain",
            177: "Jordan",
        }
    },
    "GHT": {
		courses: {
			0x21: "Baby Park",
			0x22: "Peach Beach",
			0x23: "Daisy Cruiser",
			0x24: "Luigi Circuit",
			0x25: "Mario Circuit",
			0x26: "Yoshi Circuit",
			0x28: "Mushroom Bridge",
			0x29: "Mushroom City",
			0x2a: "Waluigi Stadium",
			0x2b: "Wario Colosseum",
			0x2c: "Dino Dino Jungle",
			0x2d: "DK Mountain",
			0x2f: "Bowser's Castle",
			0x31: "Rainbow Road",
			0x32: "Dry Dry Desert",
			0x33: "Sherbet Land",
		},
		chars: {
			0x00: "Baby Mario",
			0x01: "Baby Luigi",
			0x02: "Paratroopa",
			0x03: "Koopa",
			0x04: "Peach",
			0x05: "Daisy",
			0x06: "Mario",
			0x07: "Luigi",
			0x08: "Wario",
			0x09: "Waluigi",
			0x0A: "Yoshi",
			0x0B: "Birdo",
			0x0C: "Donkey Kong",
			0x0D: "Diddy Kong",
			0x0E: "Bowser",
			0x0F: "Bowser Jr.",
			0x10: "Toad",
			0x11: "Toadette",
			0x12: "King Boo",
			0x13: "Petey Piranha",
		},
		karts: {
			0x00: "Red Fire",
			0x01: "DK Jumbo",
			0x02: "Turbo Yoshi",
			0x03: "Koopa Dasher",
			0x04: "Heart Coach",
			0x05: "Goo-Goo Buggy",
			0x06: "Wario Car",
			0x07: "Koopa King",
			0x08: "Green Fire",
			0x09: "Barrel Train",
			0x0A: "Turbo Birdo",
			0x0B: "Para-Wing",
			0x0C: "Bloom Coach",
			0x0D: "Rattle Buggy",
			0x0E: "Waluigi Racer",
			0x0F: "Bullet Blaster",
			0x10: "Toad Kart",
			0x11: "Toadette Kart",
			0x12: "Boo Pipes",
			0x13: "Piranha Pipes",
			0x14: "Parade Kart",
		}
	},
    // https://tcrf.net/Notes:Mario_Kart_7
    "MK7 DAT": {
        gliders: {
            0x00: "Super Glider",
            0x01: "Paraglider / Parafoil",
            0x02: "Peach Parasol",
            0x03: "Flower Glider",
            0x04: "Swooper / Swoop",
            0x05: "Beast Glider / Ghastly Glider",
            0x06: "Gold Glider",
        },
        tires: {
            0x00: "Standard / Normal",
            0x01: "Monster",
            0x02: "Roller",
            0x03: "Slick",
            0x04: "Slim",
            0x05: "Sponge",
            0x06: "Gold Tires",
            0x07: "Wood / Wooden",
            0x08: "Red Monster",
            0x09: "Mushroom",
        },
        karts: {
            0x00: "Standard",
            0x01: "Bolt Buggy",
            0x02: "Birthday Girl / Royal Ribbon",
            0x03: "Egg 1",
            0x04: "B Dasher",
            0x05: "Zucchini / Gherkin",
            0x06: "Koopa Clown",
            0x07: "Tiny Tug",
            0x08: "Bumble V",
            0x09: "Cact-X",
            0x0A: "Bruiser / Growlster",
            0x0B: "Pipe Frame",
            0x0C: "Barrel Train",
            0x0D: "Cloud 9",
            0x0E: "Blue Seven",
            0x0F: "Soda Jet",
            0x10: "Gold Standard / Gold Kart",
        },
        chars: {
            0x00: "Bowser",
            0x01: "Daisy",
            0x02: "Donkey Kong",
            0x03: "Honey Queen",
            0x04: "Koopa Troopa",
            0x05: "Lakitu",
            0x06: "Luigi",
            0x07: "Mario",
            0x08: "Metal Mario",
            0x09: "Mii (Male)",
            0x0A: "Mii (Female)",
            0x0B: "Peach",
            0x0C: "Rosalina",
            0x0D: "Shy Guy",
            0x0E: "Toad",
            0x0F: "Wario",
            0x10: "Wiggler",
            0x11: "Yoshi",
        },
        courses: {
            0x00: "Mario Circuit",
            0x01: "Rock Rock Mountain / Alpine Pass",
            0x02: "Cheep Cheep Lagoon / Cheep Cheep Cape",
            0x03: "Daisy Hills",
            0x04: "Toad Circuit",
            0x05: "Shy Guy Bazaar",
            0x06: "Neo Bowser City / Koopa City",
            0x07: "DK Jungle",
            0x08: "Wuhu Loop / Wuhu Island Loop",
            0x09: "Maka Wuhu / Wuhu Mountain Loop",
            0x0A: "Rosalina's Ice World",
            0x0B: "Bowser's Castle",
            0x0C: "Piranha Plant Slide / Piranha Plant Pipeway",
            0x0D: "Rainbow Road",
            0x0E: "Wario Shipyard / Wario's Galleon",
            0x0F: "Music Park / Melody Motorway",
            0x10: "Wii Coconut Mall",
            0x11: "Wii Koopa Cape",
            0x12: "Wii Maple Treeway",
            0x13: "Wii Mushroom Gorge",
            0x14: "DS Luigi's Mansion",
            0x15: "DS Airship Fortress",
            0x16: "DS DK Pass",
            0x17: "DS Waluigi Pinball",
            0x18: "GCN Dino Dino Jungle",
            0x19: "GCN Daisy Cruiser",
            0x1A: "N64 Luigi Raceway",
            0x1B: "N64 Kalimari Desert",
            0x1C: "N64 Koopa Beach / N64 Koopa Troopa Beach",
            0x1D: "GBA Bowser Castle 1",
            0x1E: "SNES Mario Circuit 2",
            0x1F: "SNES Rainbow Road",
            0x20: "Wuhu Town",
            0x21: "Honeybee Hive / Honeybee House",
            0x22: "Sherbet Rink",
            0x23: "DS Palm Shore",
            0x24: "N64 Big Donut",
            0x25: "GBA Battle Course 1",
            0x26: "Toad Circuit (Grand Prix winning cutscene)",
        }
    },
};
