export const strings = {
    gliders: [
        /*0x00*/ "Super Glider",
        /*0x01*/ "Paraglider / Parafoil",
        /*0x02*/ "Peach Parasol",
        /*0x03*/ "Flower Glider",
        /*0x04*/ "Swooper / Swoop",
        /*0x05*/ "Beast Glider / Ghastly Glider",
        /*0x06*/ "Gold Glider",
    ],
    tires: [
        /*0x00*/ "Standard / Normal",
        /*0x01*/ "Monster",
        /*0x02*/ "Roller",
        /*0x03*/ "Slick",
        /*0x04*/ "Slim",
        /*0x05*/ "Sponge",
        /*0x06*/ "Gold Tires",
        /*0x07*/ "Wood / Wooden",
        /*0x08*/ "Red Monster",
        /*0x09*/ "Mushroom",
    ],
    karts: [
        /*0x00*/ "Standard",
        /*0x01*/ "Bolt Buggy",
        /*0x02*/ "Birthday Girl / Royal Ribbon",
        /*0x03*/ "Egg 1",
        /*0x04*/ "B Dasher",
        /*0x05*/ "Zucchini / Gherkin",
        /*0x06*/ "Koopa Clown",
        /*0x07*/ "Tiny Tug",
        /*0x08*/ "Bumble V",
        /*0x09*/ "Cact-X",
        /*0x0A*/ "Bruiser / Growlster",
        /*0x0B*/ "Pipe Frame",
        /*0x0C*/ "Barrel Train",
        /*0x0D*/ "Cloud 9",
        /*0x0E*/ "Blue Seven",
        /*0x0F*/ "Soda Jet",
        /*0x10*/ "Gold Standard / Gold Kart",
    ],
    chars: [
        /*0x00*/ "Bowser",
        /*0x01*/ "Daisy",
        /*0x02*/ "Donkey Kong",
        /*0x03*/ "Honey Queen",
        /*0x04*/ "Koopa Troopa",
        /*0x05*/ "Lakitu",
        /*0x06*/ "Luigi",
        /*0x07*/ "Mario",
        /*0x08*/ "Metal Mario",
        /*0x09*/ "Mii (Male)",
        /*0x0A*/ "Mii (Female)",
        /*0x0B*/ "Peach",
        /*0x0C*/ "Rosalina",
        /*0x0D*/ "Shy Guy",
        /*0x0E*/ "Toad",
        /*0x0F*/ "Wario",
        /*0x10*/ "Wiggler",
        /*0x11*/ "Yoshi",
    ],
    courses: [
        /*0x00*/ "Mario Circuit",
        /*0x01*/ "Rock Rock Mountain / Alpine Pass",
        /*0x02*/ "Cheep Cheep Lagoon / Cheep Cheep Cape",
        /*0x03*/ "Daisy Hills",
        /*0x04*/ "Toad Circuit",
        /*0x05*/ "Shy Guy Bazaar",
        /*0x06*/ "Neo Bowser City / Koopa City",
        /*0x07*/ "DK Jungle",
        /*0x08*/ "Wuhu Loop / Wuhu Island Loop",
        /*0x09*/ "Maka Wuhu / Wuhu Mountain Loop",
        /*0x0A*/ "Rosalina's Ice World",
        /*0x0B*/ "Bowser's Castle",
        /*0x0C*/ "Piranha Plant Slide / Piranha Plant Pipeway",
        /*0x0D*/ "Rainbow Road",
        /*0x0E*/ "Wario Shipyard / Wario's Galleon",
        /*0x0F*/ "Music Park / Melody Motorway",
        /*0x10*/ "Wii Coconut Mall",
        /*0x11*/ "Wii Koopa Cape",
        /*0x12*/ "Wii Maple Treeway",
        /*0x13*/ "Wii Mushroom Gorge",
        /*0x14*/ "DS Luigi's Mansion",
        /*0x15*/ "DS Airship Fortress",
        /*0x16*/ "DS DK Pass",
        /*0x17*/ "DS Waluigi Pinball",
        /*0x18*/ "GCN Dino Dino Jungle",
        /*0x19*/ "GCN Daisy Cruiser",
        /*0x1A*/ "N64 Luigi Raceway",
        /*0x1B*/ "N64 Kalimari Desert",
        /*0x1C*/ "N64 Koopa Beach / N64 Koopa Troopa Beach",
        /*0x1D*/ "GBA Bowser Castle 1",
        /*0x1E*/ "SNES Mario Circuit 2",
        /*0x1F*/ "SNES Rainbow Road",
        /*0x20*/ "Wuhu Town",
        /*0x21*/ "Honeybee Hive / Honeybee House",
        /*0x22*/ "Sherbet Rink",
        /*0x23*/ "DS Palm Shore",
        /*0x24*/ "N64 Big Donut",
        /*0x25*/ "GBA Battle Course 1",
        /*0x26*/ "Toad Circuit (Grand Prix winning cutscene)",
    ]
};