name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run tsc
        run: tsc
      - name: Copy files
        run: mv static out; rsync -av --ignore-existing built/ out/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
